name: sakame
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- numpy
- numba
- numexpr
- scipy
- scikit-learn
- scikit-image
- matplotlib
- h5py
- ipykernel
- pandas
# Geoprocessing libraries
- xarray
- conda-forge::xesmf
- shapely
- geopandas
- rasterio
- affine
# Plotting Libraries
- pyviz::hvplot
- matplotlib
- cartopy
- pip
- pip:
    - zarr
    - jax
    - jaxlib
    - black
    - mypy
    - flake8
    - isort