name: sakame
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- numpy
- numba
- numexpr
- scipy
- scikit-learn
- matplotlib
- xarray
- h5py
- ipykernel
- pandas
- cartopy
- pip
- pip:
    - zarr
    - jax
    - jaxlib
    - black
    - mypy
    - flake8
    - isort